services:
  jappy-hub:
    platform: linux/amd64
    image: gastudil/courses:jappy-hub
    container_name: jappy_hub
    #entrypoint: sleep infinity
    hostname: jappy_hub
    ports:
      - 8000:8000
      - 10666:10666
    volumes:
      - ./hub_etc:/etc
      - ./hub_homes:/home/hub_homes
      - ./hub_examples:/home/hub_examples
      - ./jupyterhub_custom:/home/jupyterhub_custom
    networks:
      - back_net

networks:
  back_net:

