services:
  jappy-hub:
    platform: linux/amd64
    image: gastudil/courses:jappy-hub
    container_name: jappy_hub
    hostname: jappy_hub
    ports:
      - 8000:8000
      - 10000:10000
    volumes:
      - ./hub_etc:/etc
      - ./hub_homes:/home/hub_homes
      - ./hub_examples:/home/codes_examples
    networks:
      - back_net

networks:
  back_net:

