#!/bin/sh
set -e

### BEGIN INIT INFO
# Provides:           jappy_hub
# Required-Start:     $docker
# Required-Stop:      
# Default-Start:      2 3 4 5
# Default-Stop:       0 1 6
# Short-Description:  Jappy server utility
# Description:
#  Jappy is an open-source project 
# Jappy is a development environment that allows
# people learning to program in Python, C++, or Java
# to have a consistent, personal development 
# environment that doesn't affect the quality of 
# assignment submissions. It also allows them to 
# review concepts and complete programming exercises.
### END INIT INFO


# Install script
# This file should be copied to the host's /etc/init.d directory.
# The runlevels must then be updated with the command:
# 'update-rc.d jappy-hub defaults'

export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin

# Directory where the jappy server is installed
JAPPY_INSTALL=/opt/servers/jappy.hub

case "$1" in
	start)
		cd $JAPPY_INSTALL && docker compose up -d	
		;;

	stop)
		cd $JAPPY_INSTALL && docker compose down
		;;

	*)
		echo "Usage: /etc/init.d/jappy-hub {start|stop}"
		exit 1
		;;
esac

